### ISSUE TITLE
add more than just the top x subs?

### ISSUE THREAD

**Issue by ImLunaHey** [ArthurHeitmann/reddit_site_stats#1]
You should be able to pull all the subs participating in the blackout from https://www.reddit.com/r/ModCoord/wiki/index.json

**Comment by ArthurHeitmann** [comment]
I'm open to adding more. The only limit is the rate limit on the reddit API, and I don't want to break the rules.
The limit is 100 requests over 10 minutes.
- 20 are used up by the posts & comments per minute
- One requests can get 100 subreddits, so currently 1500/100 = 15. And that every 5 minute is 30 requests
So in total I'm currently using 50 / 100 requests.

I could increase the number of subs to 3500 and end up using 90% of the rate limit.
Or if I reduce the frequency to every 10 minutes I can get 7000 subs, also at 90% of the rate limit.

**Comment by ArthurHeitmann** [comment]
Actually I have decided that I will probably not be adding any more subreddits. The reasons:
- I cannot get the number of subscribers from private subreddits. Missing sub count could break some things.
- The blue subreddit status timeline would have all the data of the past 4 days missing.
- Same for the other subreddit bar chart. In addition there would be a large sudden jump in private subs.
