### ISSUE TITLE
Y Axis label on Posts and comments per minute

### ISSUE THREAD

**Issue by TechyDad** [ArthurHeitmann/reddit_site_stats#3]
Could you add labeling on the Y axis of Posts and comments per minute so it's obvious how far the drop is? Without labeling, the drop could be from 10,000 posts/comments to 9,950 (not that big of a drop) or to 1,000 (a large drop).

**Comment by ArthurHeitmann** [comment]
Done. The chart might be a bit dense on mobile in portrait orientation, but should be fine in landscape.
