### ISSUE TITLE
Dark Theme? 

### ISSUE THREAD

**Issue by DM115-rpi-win** [ArthurHeitmann/reddit_site_stats#4]
There is a lot of tiny pieces of information, dark theme would make it easier to read.

**Comment by ArthurHeitmann** [comment]
I definitely want to add a dark theme soon. There are a couple of other things I want to do first though.

**Comment by ArthurHeitmann** [comment]
Added it. You can switch between the light/dark theme by clicking the sun/moon at the beginning of the page.

**Comment by DM115-rpi-win** [comment]
Cool man, thanks!
