### ISSUE TITLE
"In blackout for" time misleading

### ISSUE THREAD

**Issue by michaelpkuhn** [ArthurHeitmann/reddit_site_stats#5]
In blackout time resets when subreddit moves from private to restricted, but restricted subs are still considered in blackout.
![image](https://github.com/ArthurHeitmann/reddit_site_stats/assets/23561727/5597ac57-b906-40cc-b69b-7f9172c26dbf)

**Comment by ArthurHeitmann** [comment]
You are totally right. I wanted to change that for a while. I renamed it to "Time since last change" and moved the column to the right, because I think the "Total blackout for" column is more important.
